// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycrbimlfaxfywjhjissz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcmJpbWxmYXhmeXdqaGppc3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzk0OTEsImV4cCI6MjA1NzkxNTQ5MX0.fxhFpGT67PmbwUgABFNTcli8KjI1LndqlEABcCWWgIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);